scripts:
  - name: Make gradlew executable
    script: |
      chmod +x gradlew
      ls -la

  - name: Clean project
    script: ./gradlew clean

  - name: Build APK
    script: ./gradlew assembleDebug
